fourth_project/fourth_app/urls.py
from django.conf.urls import url
from fourth_app import views

#template tagging
app_name = 'fourth_app'


urlpatterns =[
    url('relative/',views.relative,name='relative'),
    url('other/',views.other,name='other'),
    
]

fourth_project/fourth_project/urls.py
from django.contrib import admin
from django.urls import path
from fourth_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('fourth_app/',include('fourth_app.urls')),

]

fourth_project/fourth_app/models.py
from django.db import models

# Create your models here.

fourth_project/fourth_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request,'fourth_app/index.html',context_dict)

def other(request):
    return render(request,'fourth_app/other.html')

def relative(request):
    return render(request,'fourth_app/relative_url_templates.html')

fourth_project/templates/fourth_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <div class="container">
        <ul class="nav navbar-nav">
          <li > <a class="navbar-brand" href="{%url 'index'%}">BRAND</a> </li>
          <li><a class="navbar-link" href="{%url 'admin:index'%}">ADMIN</a></li>
          <li><a class="navbar-link" href="{%url 'fourth_app:other'%}">OTHET</a></li>

        </ul>

      </div>

    </nav>

<div class="container">
  {%block body_block%}
    <!--inherited-->
  {%endblock%}

</div>



  </body>
</html>

fourth_project/templates/fourth_app/index.html
<!DOCTYPE html>
{%extends "fourth_app/base.html"%}
  {%block body_block%}
  <h1>WELCOME TO INDEX</h1>
<h1>  {{text|cut:'hell'}}</h1>
<h1>  {{number|add:"99"}}</h1>

    {%endblock%}
  

fourth_project/templates/fourth_app/other.html
<!DOCTYPE html>
{% extends "fourth_app/base.html"%}
   {%block body_block%}
       <h1>WELCOME TO OTHER </h1>
       <h2>inherited</h2>
       {%endblock%}

fourth_project/templates/fourth_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
   <h1>WELCOME TO RELATIVE</h1>
  <a href="{% url 'fourth_app:other'%}">THE OTHER PAGE</a>
  <a href="{%url 'admin:index'%}">LINK TO ADMIN</a>
  <a href="{%url 'index'%}">LINK TO INDEX!</a>
  </body>
</html>